Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/LineLength:
  Max: 210

Style/ClassVars:
  Enabled: false

Lint/RedundantStringCoercion:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
  
Metrics/AbcSize:
  Enabled: false

Lint/Void:
  Enabled: false